### ISSUE TITLE
Investigate and encorporate typescript

### ISSUE THREAD

**Issue by stretch07** [try-supernova/supernova#34]
according to https://stackoverflow.com/questions/8407622/set-type-for-function-parameters and typescriptlang.org typescript is javascript with syntax for types. this way we can force users to input certain types of function parameters without having to check `typeof` every single time

**Comment by its-pablo** [comment]
(it isnt useless)

**Comment by its-pablo** [comment]
i'm making the decision to use jsdoc just so this can be more maintainable I think
I might add typescript someday
