### ISSUE TITLE
Replace localForage with something else

### ISSUE THREAD

**Issue by stretch07** [try-supernova/supernova#44]
subj.

**Comment by its-pablo** [comment]
Also this is cool: https://js.libhunt.com/

**Comment by its-pablo** [comment]
https://github.com/marcuswestin/store.js seems fine actually

**Comment by its-pablo** [comment]
What if I just use regular indexeddb without a lib
code would be reduced, speed would improve

**Comment by its-pablo** [comment]
yeah we're doing that
